version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/EmployeeManagement
      - PORT=5000
      - SECRETKEY=SECR3TK3Y
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BASE_URL=http://backend:5000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - BASE_URL=http://frontend:3000
    env_file:
      - ./tests/e2e/config/.env
    depends_on:
      - backend
      - frontend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  mongo-data:
